spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: hr
    password: hr
    driver-class-name: oracle.jdbc.OracleDriver
  mvc:
    view:
      prefix: /
      suffix: .jsp
  profiles:
    active: test
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis:
  type-aliases-package: com.baizhi.entity
